version: 2 # use CircleCI 2.0

jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    working_directory: ~/client
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: ./vendor/bin/phplint .
      - run: ./vendor/bin/phpunit
